routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'account/', 'as' => 'account.'], function () {
    Auth::routes();
});

Route::get('/', 'HomeController@home')->name('home');
Route::get('domain', 'HomeController@domain')->name('domain');
Route::get('support', 'HomeController@Support')->name('support');
Route::get('pk-domain', 'HomeController@PkDomain')->name('pkdomain');
Route::get('payment', 'HomeController@payment')->name('payment');
Route::get('contact-us', 'HomeController@contact')->name('contact');
Route::get('hosting', 'HomeController@host')->name('hosting');
Route::get('{type}/hosting', 'HomeController@host')->name('host');
Route::get('career', 'HomeController@career')->name('career');
Route::get('about-us', 'HomeController@AboutUs')->name('AboutUs');
Route::get('affiliates', 'HomeController@Affiliates')->name('affiliates');
Route::get('pk-prepaid-card', 'HomeController@PkPrepaidCard')->name('pkprepaidcard');
Route::get('web-development', 'HomeController@WebDevelopment')->name('webdevelopment');
Route::get('seo', 'HomeController@SEO')->name('seo');
Route::get('Services', 'HomeController@Services')->name('services');
Route::get('WhoisDomain', 'HomeController@WhoisDomain')->name('whoisdomain');
Route::get('faqs', 'HomeController@FAQ')->name('faq');
Route::get('pk-hosting/cart', 'HomeController@PkHostingCart')->name('pkhostingcart');

Route::group(['prefix' => 'admin/', 'as' => 'admin.'], function () {
    Route::middleware('guest:admin')->group(function () {
        Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login.form');
        Route::post('login', 'Auth\AdminAuthController@login')->name('login');
    });
    Route::middleware('auth:admin')->group(function () {
        Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');
        Route::get('', 'AdminController@home')->name('home');
        Route::resource('packages', 'PackageController')->except(['show', 'destroy']);
    });
});

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Admin Panel</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/sidebar.css') }}">
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous">
    </script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous">
    </script>
    @yield('styles')
</head>

<body>
    @auth('admin')
        <div class="wrapper">
            <nav id="sidebar">
                <div class="sidebar-header">
                    <h3>Panel</h3>
                </div>
                <ul class="list-unstyled components">
                    <li>
                        <a href="{{ route('admin.packages.index') }}">Packages</a>
                    </li>
                    {{-- <li>
                        <a href="#questionSubmenu" data-toggle="collapse" aria-expanded="false"
                            class="dropdown-toggle">Main</a>
                        <ul class="collapse list-unstyled" id="questionSubmenu">
                            <li>
                                <a href="#">List</a>
                            </li>
                        </ul>
                    </li> --}}
                </ul>
            </nav>
            <div id="content">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">
                        <button type="button" id="sidebarCollapse" class="btn btn-info">
                            <i class="fas fa-align-left"></i>
                        </button>
                        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fas fa-align-justify"></i>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="nav navbar-nav ml-auto">
                                <li class="nav-item">
                                    <div class="dropdown">
                                        <a class="btn btn-dark" href="#" role="button" data-toggle="collapse"
                                            data-target="#dropdownMenuLink" aria-controls="navbarSupportedContent"
                                            aria-expanded="false" aria-label="Toggle navigation">Admin</a>
                                        <div class="dropdown-menu dropdown-menu-right" id="dropdownMenuLink">
                                            <a class="dropdown-item" href="javascript:void()"
                                                onclick="document.getElementById('logout').submit()">
                                                Logout
                                                <form id="logout" action="{{ route('admin.logout') }}" method="POST"
                                                    class="-dnone">@csrf</form>
                                            </a>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <div class="container my-2">
                    @yield('content')
                </div>
            </div>
        </div>
    @else
        <div class="container">
            <div class="my-4">
                <div class="row justify-content-center">
                    <div class="col-md-5">
                        @yield('content')
                    </div>
                </div>
            </div>
        </div>
    @endauth
</body>
<script src="{{ asset('js/app.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#sidebarCollapse').on('click', function() {
            $('#sidebar').toggleClass('active');
        });
    });
</script>
@yield('scripts')

</html>

resources/views/admin/dashboard.blade.php
@extends('admin.app')

@section('content')
    Content
@endsection