routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'account/', 'as' => 'account.'], function () {
    Auth::routes();
});

Route::get('/', 'HomeController@home')->name('home');
Route::get('domain', 'HomeController@domain')->name('domain');
Route::get('support', 'HomeController@Support')->name('support');
Route::get('pk-domain', 'HomeController@PkDomain')->name('pkdomain');
Route::get('payment', 'HomeController@payment')->name('payment');
Route::get('contact-us', 'HomeController@contact')->name('contact');
Route::get('hosting', 'HomeController@host')->name('hosting');
Route::get('{type}/hosting', 'HomeController@host')->name('host');
Route::get('career', 'HomeController@career')->name('career');
Route::get('about-us', 'HomeController@AboutUs')->name('AboutUs');
Route::get('affiliates', 'HomeController@Affiliates')->name('affiliates');
Route::get('pk-prepaid-card', 'HomeController@PkPrepaidCard')->name('pkprepaidcard');
Route::get('web-development', 'HomeController@WebDevelopment')->name('webdevelopment');
Route::get('seo', 'HomeController@SEO')->name('seo');
Route::get('Services', 'HomeController@Services')->name('services');
Route::get('WhoisDomain', 'HomeController@WhoisDomain')->name('whoisdomain');
Route::get('faqs', 'HomeController@FAQ')->name('faq');
Route::get('pk-hosting/cart', 'HomeController@PkHostingCart')->name('pkhostingcart');

Route::group(['prefix' => 'admin/', 'as' => 'admin.'], function () {
    Route::middleware('guest:admin')->group(function () {
        Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login.form');
        Route::post('login', 'Auth\AdminAuthController@login')->name('login');
    });
    Route::middleware('auth:admin')->group(function () {
        Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');
        Route::get('', 'AdminController@home')->name('home');
        Route::resource('packages', 'PackageController')->except(['show', 'destroy']);
    });
});

resources/views/layouts/footer.blade.php
<div id="footer">
    <div class="container" style="background:#fff">
        <div class="content-adj">
            <div class="ft_rep"><span class="ft_heading">Hosting</span>
                <ul>
                    <li><a href="{{ route('host', 'web') }}" class="ft_link">Web Hosting</a></li>
                    <li><a href="{{ route('host', 'unlimited') }}" class="ft_link">Unlimited Hosting</a></li>
                    <li><a href="{{ route('host', 'ssd') }}" class="ft_link">SSD Hosting</a></li>
                    <li><a href="{{ route('host', 'business') }}" class="ft_link">Business Hosting</a></li>
                    <li><a href="{{ route('host', 'pk-domain') }}" class="ft_link">Hosting with Free .COM</a></li>
                    <li><a href="{{ route('host', 'reseller') }}" class="ft_link">Reseller Hosting</a></li>
                </ul>
            </div>
            <div class="ft_rep"><span class="ft_heading">Services</span>
                <ul>
                    <li><a href="{{route('domain')}}" class="ft_link">Domains</a></li>
                    <li><a href="{{route('pkdomain')}}" class="ft_link">PK Domains</a></li>
                    <li><a href="{{route('pkprepaidcard')}}" class="ft_link">PKNIC Prepaid Cards</a></li>
                    <li><a href="{{route('webdevelopment')}}" class="ft_link">Web Development</a></li>
                    <li><a href="{{route('seo')}}" class="ft_link">SEO</a></li>
                    <li><a href="{{route('services')}}" class="ft_link">Services</a></li>
                </ul>
            </div>
            <div class="ft_rep"><span class="ft_heading">Important</span>
                <ul>
                    <li><a href="{{ route('payment') }}">Payment Options</a></li>
                    <li><a href="{{route('affiliates')}}">Affiliates</a></li>
                    <li><a href="https://blog.easyhost.pk/">Blog</a></li>
                    <li><a href="{{route('whoisdomain')}}">Domain Whois</a></li>
                    <li><a href="{{route('faq')}}">FAQs</a></li>
                    <li><a href="{{route('career')}}">Careers</a></li>
                </ul>
            </div>
            <div class="ft_rep" style="width:25%">
                <span class="ft_heading">Subscribe Us</span>
                <p id='subscribe' style='margin-bottom: 10px'>Submit email to get the special discounts, be the first to
                    know our deals:</p>
                <form method="post" action="#subscribe">
                    <input name="field_0" type="email" placeholder="yourname@gmail.com"
                        style="padding:5px 2px; font-weight: bold; margin-bottom: 10px; width: 70%">
                    <input type="submit" name="submitBtn" value="Subscribe"
                        style="padding: 5px 0px; font-weight: bold; width: 25%">
                </form>
            </div>
            <p style="text-align: center">
                <a href="new-year-sale80cc.html?source=footer">New Year Sale</a> |
                <a href="tos.html">Terms Of Services</a> |
                <a href="tos.html#money-back-policy">Money Back Policy</a> |
                <a href="tos.html#privacy-policy">Privacy Policy</a> |
                <a href="discounts.html">Discounts</a> |
                <a href="sitemap.html">Sitemap</a>
            </p>
            <p style="text-align: center">Copyright &copy; 2016-2020 OvoHost. All Rights Reserved.</p>
        </div>
        @if (request()->is('/'))
            <div class="clear"></div>
            <div style="background:#f1f1f1; padding:20px 10px;">
                <h3 style="font-size:14px; line-height:20px">Domain Name and Hosting</h3>
                <p style="font-size:13px; line-height:18px">At OvoHost, you can select from the wide range to top class
                    Domain Name and Hosting packages for your website starting for as low as SR.2,200/yr including free
                    domain and SSL. Looking for reliable Web Hosting in Saudi Arabia? look no further, OvoHost has
                    everything
                    you will need to get your webpage online within 15 minutes.</p>
                <h3 style="font-size:14px; line-height:20px; margin-top:10px">Com Domain Name Registration</h3>
                <p style="font-size:13px; line-height:18px">OvoHost is the leading .Com domain name registration service
                    provider in Saudi Arabia offering the cheapest .Com rates (SR.2,350/2yr) and the fastest registration
                    time in
                    industry. All .Com domains registered with us are activated within 15 minutes and customer has 100%
                    ownership.</p>
                <h3 style="font-size:14px; line-height:20px; margin-top:10px">OvoHost Reviews & Comparison vs Other
                    Providers</h3>
                <p style="font-size:13px; line-height:18px">Ovohost has been in the industry since 2009 and have service
                    1000s of customers. Unlike other web hosting companies in Saudi Arabia, OvoHost owns servers and ensure
                    the
                    highest quality. You can <a href="https://whmedium.com/company/easyhost.pk" target="_blank">find
                    OvoHost's reviews at WHmedium</a></p>
            </div>
        @endif
    </div>
</div>

resources/views/layouts/footertop.blade.php
@if (!request()->is('account/*'))
    <div id="customers">
        <h3>Our customers are our top priority!</h3>
        <p>OvoHost proudly ofers web hosting & domain services to 1000s of startups, bloggers, e-commerce
            platform
            SMEs in
            Saudi Arabia since 2009.
            Here is a quick overview of the services we delivered this year:</p>

        <div id="highlights">
            <div class="highlight-block">
                <p class="high">5+ Million</p>
                <p class="low">Pages Served</p>
            </div>

            <div class="highlight-block">
                <p class="high">1+ Million</p>
                <p class="low">Emails Sent!</p>
            </div>

            <div class="highlight-block">
                <p class="high">~99.91%</p>
                <p class="low">Uptime Recorded!</p>
            </div>

            <div class="clear"></div>
        </div>

        <div class="clear"></div>
        <p style="text-align: center; margin-top: 20px"><img src="{{ asset('images/feedback.png') }}"
                alt="feedback"><br>
            <i>I moved to
            ovohost.com from other
                Saudi Arabia hosting company 3 months ago, their webhosting is amazing and support is unbeatable,
                highly
                recommended!</i> - <strong>CEO - Saleshub</strong><br> <i>OvoHost activated my account within
                10
                minutes as
                committed, transferred my data and helped me with website security. I made right decision to
                select
                ovohost.com</i> - <strong>Atta Khan</strong>
        </p>
        <p style="text-align:center"><a href="https://whmedium.com/company/easyhost.com" target="_blank">OvoHost's
                reviews
                at WHmedium</a></p>

    </div>
@endif
<div id="footertop">
    <div class="col-md-3">
        <figure><img src="{{ asset('images/WhatsApp_Footer.png') }}" alt="Image"></figure>
        <dl>
            <dt>WhatsApp</dt>
            <dd>+966 59 478 8122</dd>
           
        </dl>
    </div>
    <div class="col-md-3">
        <figure><img src="{{ asset('images/email_Footer.png') }}" alt="Image"></figure>
        <dl>
            <dt>Email</dt>
            <dd>info@ovohost.com</dd>
            <dd>support@ovohost.com</dd>
        </dl>
    </div>
    <div class="col-md-3">
        <figure><img src="{{ asset('images/Phone_Footer.png') }}" alt="Image"></figure>
        <dl>
            <dt>Sales</dt>
            <dd>+966 59 478 8122</dd>
            
        </dl>
    </div>
    <div class="col-md-3">
        <figure><img src="{{ asset('images/Working-Hours_Footer.png') }}" alt="Image"></figure>
        <dl>
            <dt>Working hours</dt>
            <dd>Support: Ticket / Email</dd>
            <dd>Call: 9am - 7pm</dd>
        </dl>
    </div>
</div>

resources/views/layouts/header.blade.php
<style>
   ul{
        padding: 0;
        list-style: none;
    }
    ul li{
        display: inline-block;
        position: relative;
        line-height: 50px;
        text-align: left;
    }
    ul li a{
        display: block;
        padding: 8px 25px;
        color: #333;
        text-decoration: none;
    }
    ul li a:hover{
        color: #fff;
        background: #939393;
    }
    ul li ul.dropdown{
        min-width: 100%; /* Set width of the dropdown */
        background: #f2f2f2;
        display: none;
        position: absolute;
        z-index: 999;
        left: 0;
    }
    ul li:hover ul.dropdown{
        display: block;	/* Display the dropdown */
      
      padding:0px;
    }
    ul li ul.dropdown li{
        display: block;
    }
</style>
<!--<style>
    @media all and (min-width: 992px) {
	.nav-item .dropdown-menu{ display: none; }
	.nav-item:hover .nav-link{   }
	.nav-item:hover .dropdown-menu{ display: block; }
	.nav-item .dropdown-menu{ margin-top:0; }
}
</style> -->
<div id="notification">
    <div class="container">
        <div class="not-right">
            <ul>
                <li>
                    <p style="padding-top: 7px;">24x7 Sales: +966 59 478 8122</p>
                </li>
                <li><a href="{{ route('account.register') }}">Register</a></li>
                <li><a href="{{ route('account.login') }}">Login</a></li>
                <li><a href="account/index804a.html">Support</a></li>
                <li><a href="{{ route('contact') }}">Contact Us</a></li>
            </ul>
        </div>
        <div class="not-left">
            <p style="padding-top: 7px;">Saudi Arabia's #1 affordable Web Hosting & Com Domain provider.</p>
        </div>
        <div class="clear"></div>
    </div>
</div>

<div id="header">
    <div class="container" style="background: #fff">
        <div id="logo">
            <a href="{{ route('home') }}">
                <img width="150" src="{{ asset('images/logo-sm.png') }}" alt="ovohost.pk"/>
            </a>
        </div>

        <div id="top-area">
            <div id="menu-icon" style="cursor:pointer" onclick="openNav()">&nbsp;&#9776;&nbsp;</div>
            <div id="mySidenav" class="sidenav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <a href="{{ route('home') }}">Home</a>
                <a href="{{ route('host', 'web') }}">Web Hosting</a>
                <a href="{{ route('host', 'unlimited') }}">Unlimited Hosting
                    <sup
                        style="font-size: 12px; padding: 1px 5px; background-color:#2fb145; color: white; border-radius: 2px">HOT</sup>
                </a>
                <a href="{{ route('host', 'pk-domain') }}">.COM + Hosting</a>
                <a href="{{ route('host', 'ssd') }}">SSD Hosting</a>
                <a href="reseller-hosting.html">Reseller Hosting</a>
                <a href="{{ route('domain') }}">Domains</a>
                <a href="pk-domains.html">COM Domains</a>
                <a href="{{ route('payment') }}">Payments</a>
                <a href="contact.html">Contact Us</a>
                <a href="account/index804a.html">Client Login</a>
                <a href="account/register.html">Register</a>
            </div>

            <script>
                function openNav() {
                    document.getElementById("mySidenav").style.width = "200px";
                    document.getElementById("menu-icon").style.marginLeft = "0";
                }

                function closeNav() {
                    document.getElementById("mySidenav").style.width = "0";
                    document.getElementById("menu-icon").style.marginLeft = "0";
                }
            </script>

            <div id="menu">
                <div>
                    <ul id="menu-main" class="menu">
                        <li><a href="{{ route('home') }}">Home</a></li>
                        <!-- <li><a href="{{ route('host', 'web') }}">Hosting</a></li> -->
                        <!-- <li class="nav-item dropdown">
                                <a class="nav-link  dropdown-toggle" href="#" data-bs-toggle="dropdown">  Hover me  </a>
                                    <ul class="dropdown-menu">
                                    <ol><a class="dropdown-item" href="#"> Submenu item 1</a></ol>
                                    <ol><a class="dropdown-item" href="#"> Submenu item 2 </a></ol>
                                    <ol><a class="dropdown-item" href="#"> Submenu item 3 </a></ol>
                                    </ul>
                        </li> -->
                        <li>
                            <a href="{{ route('hosting') }}">Hosting </a>
                            <ul class="dropdown">
                                {{-- <li><a href="{{ route('host', 'web') }}">Web Hosting</a></li>
                                <li><a href="{{ route('host', 'unlimited') }}">Unlimited Hosting</a></li> --}}
                                <!-- <li><a href="#">Printers</a></li> -->
                            </ul>
                        </li>
                        <li><a href="{{ route('host', 'unlimited') }}">Unlimited Hosting <sup style="font-size: 12px; padding: 1px 5px; background-color:#2fb145; color: white; border-radius: 2px">HOT</sup></a>
                        </li>
                        <!-- <li><a href="{{ route('host', 'pk-domain') }}">.COM + Hosting</a></li> -->
                        <!-- <li><a href="{{ route('host', 'ssd') }}">SSD</a></li> -->
                        <li><a href="{{ route('domain') }}">Domains</a></li>
                        <li><a href="{{ route('payment') }}">Payments</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>